spring.application.name=figuritas

# Database
spring.datasource.url=jdbc:sqlite:figuritas.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Archivos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# === PROPIEDADES PROPIAS DE LA APLICACIÓN ===

# Access Tokens
app.auth.access-token.secret=01234567890123456789012345678901
app.auth.access-token.duration-minutes=99999

# Data Initialization
app.data.seed=42
app.data.user-count=20
app.data.base-latitude=-32.88968097552617
app.data.base-longitude=-68.8445692104641
app.data.position-offset=0.05
